export enum QUERY_KEY {
  GET_PROFILE = 'GET_PROFILE',
}

export enum LOCAL_STORAGE_KEY {
  ACCESS_TOKEN = `ACCESS_TOKEN`,
  REFRESH_TOKEN = `REFRESH_TOKEN`,
  IS_AUTHENTICATED = 'IS_AUTHENTICATED',
  SHOP_ID = 'SHOP_ID',
}
